MariaStudyGroup/Models/StudyGroupMember.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MariaStudyGroup.Models
{
    public class StudyGroupMember
    {
        [Key]
        public string StudentNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string MyLink { get; set; }
    }
}

MariaStudyGroup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MariaStudyGroup.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MariaStudyGroup/Controllers/StudyGroupController.cs
using MariaStudyGroup.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MariaStudyGroup.Controllers
{
    public class StudyGroupController : Controller
    {
        // GET: StudyGroup
        public ActionResult Index()
        {
            List<StudyGroupMember> members = new List<StudyGroupMember>
            {
                new StudyGroupMember { StudentNumber = "u22749536", Name = "Maria", Surname = "Mbambu", EmailAddress = "maria.mbambu@tuks.co.za", MyLink = "/HTML/Maria.html" },
                new StudyGroupMember { StudentNumber = "u24595901", Name = "Petrus", Surname = "Chabedi", EmailAddress = "petrus.chabedi@tuks.co.za", MyLink = "/HTML/Petrus.html" },
                new StudyGroupMember { StudentNumber = "u22557173", Name = "Masilo", Surname = "Makola", EmailAddress = "masilo.makola@tuks.co.za", MyLink = "/HTML/Masilo.html" },
                new StudyGroupMember { StudentNumber = "u22761421", Name = "Maria Lynn", Surname = "Vewesse", EmailAddress = "maria.vewesse@tuks.co.za", MyLink = "/HTML/Lynn.html" },
                new StudyGroupMember { StudentNumber = "u23578140", Name = "Kopano", Surname = "Moloi", EmailAddress = "kopano.moloi@tuks.co.za", MyLink = "/HTML/Kopano.html" }
            };

            return View(members);
        }
    }
}

MariaStudyGroup/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

MariaStudyGroup/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

MariaStudyGroup/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

MariaStudyGroup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="~/wwwroot/Style.css">
    @Styles.Render("~/wwwroot/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
     <div class="container">
        <a class="navbar-brand" href="~/Home/Index">Simple Starting Sample</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav"></ul>
        </div>
     </div>
                
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">List of Members ▼</button>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Complete List of Members", "Index", "StudyGroup")</li>
                <li><a href="~/HTML/Maria.html">Maria</a></li>
                <li><a href="~/HTML/Petrus.html">Petrus</a></li>
                <li><a href="~/HTML/Masilo.html">Masilo</a></li>
                <li><a href="~/HTML/Lynn.html">Lynn</a></li>
                <li><a href="~/HTML/Kopano.html">Kopano</a></li>
            </ul>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MariaStudyGroup/Views/StudyGroup/Index.cshtml
@model List<MariaStudyGroup.Models.StudyGroupMember>

@{
    ViewBag.Title = "Study Group Members";
}

<h2>Study Group Members</h2>

<link href="@Url.Content("~/wwwroot/Style.css")" rel="stylesheet" type="text/css" />

<table border="1">
    <thead>
        <tr>
            <th>Student Number</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Email Address</th>
            <th>Link to Personal Page</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var member in Model)
        {
            <tr>
                <td>@member.StudentNumber</td>
                <td>@member.Name</td>
                <td>@member.Surname</td>
                <td>@member.EmailAddress</td>
                <td>
                    <a href="@Url.Content(member.MyLink)" class="btn btn-primary" target="_blank">LINK</a>
                </td>
            </tr>
        }
    </tbody>
</table>